### ISSUE TITLE
Change button click sound

### ISSUE THREAD

**Issue by codeboyfriend** [codeboyfriend/Quiz#4]

**Comment by zialink** [comment]
Please assign me to this issue, also I'll like to know the sound you'll like to use

**Comment by codeboyfriend** [comment]
Sound with like 0.5s duration

**Comment by zialink** [comment]
Ok

**Comment by zialink** [comment]
I have changed the button click sound. See if you are ok with the sound or if I should use another

**Comment by codeboyfriend** [comment]
Give the repo a star nd PR will be merge
